Fixing brain phantom values
JuliaHealth/KomaMRI.jl pull request #465
Opened 2024-08-19 21:37 UTC by gsahonero

This PR is to fix #464

2024-08-19 22:13 UTC, cncastillo requested changes
Brainweb is already referenced in the documentation:

> Creates a three-dimentional brain Phantom struct. Default ss=4 sample spacing is 2 mm. Original file (ss=1) sample spacing is .5 mm.
> 
> References
> 
>     B. Aubert-Broche, D.L. Collins, A.C. Evans: "A new improved version of the realistic digital brain phantom" NeuroImage, in review - 2006
>     B. Aubert-Broche, M. Griffin, G.B. Pike, A.C. Evans and D.L. Collins: "20 new digital brain phantoms for creation of validation image data bases" IEEE TMI, in review - 2006
>     https://brainweb.bic.mni.mcgill.ca/brainweb

These are the parameters I used (Aubert-Broche, B. et al., 2006a)

https://github.com/JuliaHealth/KomaMRI.jl/blob/v0.1-alpha/src/data/Brain2DParameters.png
![image](https://github.com/user-attachments/assets/4228cef0-bc47-456f-befd-c1c9cd924a42)

The 00 for the muscle must be a typo in the table. The skin value I could have changed on purpose (see JEMRIS's brain phantom).

Please check that phantom3D also has these changes.

2024-08-19 22:13 UTC, cncastillo commented on KomaMRIBase/src/datatypes/Phantom.jl
> +- The T1 value of SKIN/MUSCLE is different between (BrainWeb) and (Aubert-Broche, B. et al., 2006a), we used the latter one.
Remove "Reproducibilty notes". Do not modify previous citations; just add more specific link to brainweb parameters.

2024-08-20 01:00 UTC, gsahonero reviewed
Updates according to requested changes.

2024-08-20 03:04 UTC, cncastillo approved these changes

2024-08-20 03:05 UTC, merged